
{{- range .Values.bitwarden.secrets }}
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bw-{{ .name }}
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bw-{{ .name }}
  namespace: {{ .namespace }}
spec:
  organizationId: {{ .organizationId }}
  secretName: {{ .secretName }}
  {{- if .createMap }}
  map:
  {{ range .createMap }}
    - bwSecretId: {{ .bwSecretId }}
      secretKeyName: {{ .secretKeyName }}
  {{ end }}
  {{- end }}
  authToken:
    {{- if .authToken }}
      secretName: {{ .secretName }}
      secretKey: {{ .secretKey }}
    {{- else }}
      secretName: bw-auth-token
      secretKey: token
    {{- end }}
{{ end }}